src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/t3_Products_Test.cls
@isTest
private class t3_Products_Test {
	
	@isTest static void updateInventory_test() {
		// Implement test code

		fflib_ApexMocks mocks = new fflib_ApexMocks();
		fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

		// Given
		Product__c p = t3_ObjectCreator.createProduct();

		Map<Id, Decimal> mapPs = new Map<Id, Decimal>();
		mapPs.put(p.Id, 10);

		List<Product__c> testPList = new List<Product__c> { p };
		t3_Application.UnitOfWork.setMock(uowMock);

		// When
		t3_iProducts products = 
			t3_Products.newInstance(testPList);
		
		products.updateInventory( uowMock, mapPs );

		// Then
		((fflib_ISObjectUnitOfWork) 
			mocks.verify(uowMock, 1)).registerDirty(p);
		System.assertEquals(90, p.Inventory__c);
	}	


}