src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/t3_Products.cls
public class t3_Products extends fflib_SObjectDomain implements t3_iProducts{
	
	public static T3_iProducts newInstance(List<Product__c> sObjectList)
	{
		return (T3_iProducts) t3_Application.Domain.newInstance(sObjectList);
	}

	public t3_Products(List<Product__c> sObjectList)
	{
		super(sObjectList);
	}
	
	public void updateInventory(fflib_ISObjectUnitOfWork uow, Map<Id,Decimal> amounts ){

		for(Product__c product : (List<Product__c>) Records)
		{
			system.debug(product);
			system.debug(amounts.get(product.id));
			product.Inventory__c -= amounts.get(product.id);
			uow.registerDirty(product);
		}

	} 

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new t3_Products(sObjectList);
		}
	}

}